### ISSUE TITLE
Layout render incorrect when using browser back navigation

### ISSUE THREAD

**Issue by mad-raz** [sferik/rails_admin#2113]
In the cases where the admin page has one of the following components `Select` or `Multi-select` if I opened the model for edits then use the back navigations (via browser) then use the forward navigation (via browser)... the components are added to the form resulting in many components for the same field

check the attached gif for better explaination
![rails_admin_issue](https://cloud.githubusercontent.com/assets/347712/5093393/9f56435c-6f60-11e4-9284-2f5173a772f1.gif)

**Comment by fmh** [comment]
have a same issue, it's a bug with jquery.pjax when browser history back/forward

**Comment by mshibuya** [comment]
Fixed by #2678.

**Comment by satkar-seanergy** [comment]
@mshibuya I am using `'rails_admin', '~> 3.0.0'` and I see this issue. 
 I did check https://github.com/railsadminteam/rails_admin/blob/v3.0.0/src/rails_admin/filtering-select.js#L31-L33 comment says 
```
autocomplete field will be cached which causes duplicate fields to be generated.
```
So is this issue still need some work to be done?

**Comment by mshibuya** [comment]
No. The comment is just explaining the reason of that implementation.
Try with the latest release `3.1.0.rc2`, and if it doesn't fix please open another issue.

**Comment by satkar-seanergy** [comment]
@mshibuya as suggested opened a new but since I see issue is still reproducible while using `rails_admin 3.1.0.rc2` https://github.com/railsadminteam/rails_admin/issues/3570
